### ISSUE TITLE
My code error

### ISSUE THREAD

**Issue by LORD7Chaos** [i-xiaotian/AvaritiaItem#1]
Why is it not working?

#loader avaritiaitem  

import mods.avaritiaitem.AvaritiaItemBuilder;
import mods.avaritiaitem.ItemPrimer;

print("STARTING custom_avaritia_items.zs");

AvaritiaItemBuilder.registerItem("infinity_singularity", 64, "infinity_singularity");
infinity_singularity.shouldDrawHalo(true);
infinity_singularity.haloSize(8);
infinity_singularity.haloTextures("halo_image");
infinity_singularity.shouldDrawPulse(true);
infinity_singularity.create();

print("ENDING custom_avaritia_items.zs");

**Comment by i-xiaotian** [comment]
I will release a tutorial tomorrow.
your script has some errors
the haloTextures and mask image should put in resources folder('.minecraft/resources/avaritiaitem/textures/items').
In the mask image, the areas that do not show the universe should be pure black (000000). The areas that need to show the universe should only use shades of gray, specifically colors selected from the leftmost column of the palette (the colors will be in the form of 'ababab', and you'll recognize them when you select, e.g., 9e9e9e).
Here is the potentially correct script.

````
#loader avaritiaitem

import mods.avaritiaitem.AvaritiaItemBuilder;
import mods.avaritiaitem.ItemPrimer;

print("STARTING custom_avaritia_items.zs");

val primer = AvaritiaItemBuilder.registerItem("infinity_singularity", 64, "infinity_singularity");
primer.shouldDrawHalo(true);
primer.haloSize(8);
primer.haloTextures("halo_image");
primer.shouldDrawPulse(true);
primer.create();

print("ENDING custom_avaritia_items.zs");
````

or 

````
#loader avaritiaitem

import mods.avaritiaitem.AvaritiaItemBuilder;
import mods.avaritiaitem.ItemPrimer;

print("STARTING custom_avaritia_items.zs");

AvaritiaItemBuilder.registerItem("infinity_singularity", 64, "infinity_singularity")
    .shouldDrawHalo(true)
    .haloSize(8)
    .haloTextures("halo_image")
    .shouldDrawPulse(true)
    .create();

print("ENDING custom_avaritia_items.zs");
````

**Comment by LORD7Chaos** [comment]
Thank you, nice kind man
