### ISSUE TITLE
How do I make halo noise like neutronium ingot?

### ISSUE THREAD

**Issue by LORD7Chaos** [i-xiaotian/AvaritiaItem#2]
And nothing works
It may seem that I'm stupid, but I know contentweaker by 80%, but this mod is new

val primer4 = AvaritiaItemBuilder.registerItem("sky_ingot", 64, "sky_ingot");
primer4.haloSize(8);
primer4.haloTextures("halo_noise");
primer4.create();

**Comment by i-xiaotian** [comment]
set shouldDrawHalo(true) and download the latest release, it will be work

**Comment by LORD7Chaos** [comment]
It works
